// Pure date, pay and letter helpers. Dates are ISO strings (YYYY-MM-DD) handled in UTC to avoid time zone shifts.
const DAY = 86_400_000;

export function parseISO(s: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s.trim());
  if (!m) return null;
  const y = Number(m[1]), mo = Number(m[2]) - 1, d = Number(m[3]);
  const date = new Date(Date.UTC(y, mo, d));
  return date.getUTCMonth() === mo && date.getUTCDate() === d ? date : null;
}
export const toISO = (d: Date) => d.toISOString().slice(0, 10);
export const addDays = (iso: string, n: number) => toISO(new Date(parseISO(iso)!.getTime() + n * DAY));
export const daysBetween = (from: string, to: string) => Math.round((parseISO(to)!.getTime() - parseISO(from)!.getTime()) / DAY);
export function todayISO(now = new Date()) {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())}`;
}
export const longDate = (iso: string) => {
  const d = parseISO(iso);
  return d ? d.toLocaleDateString("en-US", { timeZone: "UTC", month: "long", day: "numeric", year: "numeric" }) : iso;
};
export const isLeap = (y: number) => (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;

/** Notice due date per LOA-1.1: 4 weeks (28 days) before the planned first day. */
export const noticeDueBy = (start: string) => addDays(start, -28);

/** Next occurrence of the anniversary month and day on or after today. A 29 February anniversary falls on 28 February in non-leap years. */
export function nextAnniversary(start: string, today: string): string {
  const s = parseISO(start)!, t = parseISO(today)!;
  const m = s.getUTCMonth(), d = s.getUTCDate();
  const inYear = (y: number) => toISO(new Date(Date.UTC(y, m, m === 1 && d === 29 && !isLeap(y) ? 28 : d)));
  const thisYear = inYear(t.getUTCFullYear());
  return thisYear >= today ? thisYear : inYear(t.getUTCFullYear() + 1);
}

export const payBands: Record<string, number[]> = {
  "Band 3": [40, 42, 44, 46],
  "Band 4": [45, 47.5, 50, 52.5],
  "Band 5": [50, 53, 56, 59],
};
/** Per BC-2.2: lowest step not less than the current rate; the top step when the rate is above every step. */
export function transferPlacement(rate: number, band: string) {
  const steps = payBands[band] ?? [];
  const i = steps.findIndex((x) => x >= rate);
  if (i < 0) return { step: steps.length, rate: steps[steps.length - 1] ?? 0, aboveTop: true };
  return { step: i + 1, rate: steps[i]!, aboveTop: false };
}
export const money = (n: number) => `$${n.toFixed(2)}`;

export type LetterData = {
  name: string;
  id?: string | undefined;
  title: string;
  status: string;
  start: string;
  purpose: string;
  purposeOther?: string | undefined;
  include: string[];
  rate?: string | undefined;
  hours?: string | undefined;
  contractEnd?: string | undefined;
  noc?: string | undefined;
  addressee: string;
  recipient?: string | undefined;
};
export type LetterText = { date: string; addressee: string; re: string; paragraphs: string[]; closing: string[]; footer: string };

export function buildLetter(d: LetterData, today: string): LetterText {
  const body = [
    `This letter confirms that ${d.name} is employed by Waterloo Regional Health Network as a ${d.title} on a ${d.status.toLowerCase()} basis.`,
    `${d.name} began employment on ${longDate(d.start)}.`,
  ];
  if (d.include.includes("Salary") && d.rate) body.push(`Their rate of pay is ${d.rate}.`);
  if (d.include.includes("Hours of work") && d.hours) body.push(`Their regular hours of work are ${d.hours}.`);
  if (d.include.includes("Contract dates") && d.contractEnd) body.push(`Their current contract runs from ${longDate(d.start)} to ${longDate(d.contractEnd)}.`);
  if (d.include.includes("NOC code") && d.noc) body.push(`The National Occupation Classification (NOC) code for this position is ${d.noc}.`);
  const paragraphs = [body.join(" ")];
  const purpose = d.purpose === "Other" ? d.purposeOther?.trim() : d.purpose.toLowerCase();
  if (purpose) paragraphs.push(`This letter is provided at the employee's request for ${purpose} purposes.`);
  return {
    date: longDate(today),
    addressee: d.addressee === "A named recipient" && d.recipient ? d.recipient : "To whom it may concern",
    re: `Re: Employment verification for ${d.name}${d.id ? ` (${d.id})` : ""}`,
    paragraphs,
    closing: ["Sincerely,", "People Operations", "Waterloo Regional Health Network"],
    footer: "Synthetic sample generated by the HR Research Assistant prototype. Not an official WRHN document.",
  };
}
