// Builds the real PDFs with jsPDF (no mocks) and inspects the bytes. Runs in jsdom, where the logo fetch fails and the text header is used.
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { downloadForm, letterPdf } from "./hr-pdf";
import { letterData } from "./hr-flow-engine";

const readBlob = (blob: Blob) =>
  new Promise<string>((res, rej) => {
    const fr = new FileReader();
    fr.onload = () => res(Buffer.from(fr.result as ArrayBuffer).toString("latin1"));
    fr.onerror = () => rej(fr.error);
    fr.readAsArrayBuffer(blob);
  });

/** Reads the text a PDF viewer would show: unescapes string literals and joins wrapped lines. */
const pdfText = (raw: string) =>
  [...raw.matchAll(/\(((?:\\.|[^\\)])*)\)\s*Tj/g)]
    .map((m) => m[1]!.replace(/\\([()\\])/g, "$1"))
    .join(" ")
    .replace(/\s+/g, " ");

const data = letterData({
  name: "Jane Doe",
  id: "E0123",
  title: "Registered Nurse",
  status: "Full-time",
  start: "2019-03-04",
  purpose: "Immigration",
  include: ["Salary", "Hours of work", "NOC code"],
  rate: "$52.00 per hour (synthetic sample)",
  hours: "37.5 hours per week",
  noc: "31301",
  addressee: "To whom it may concern",
});

describe("letter PDF", () => {
  it("is a US Letter PDF containing the name, title, NOC code and the footer", async () => {
    const r = await letterPdf(data, "2026-10-07");
    expect(r.filename).toBe("employment-letter-doe-sample.pdf");
    const raw = await readBlob(r.blob);
    expect(raw.startsWith("%PDF-")).toBe(true);
    expect(raw).toMatch(/\/MediaBox \[0 0 612\.? 792\.?\]/); // US Letter in points
    const text = pdfText(raw);
    for (const needle of [
      "Re: Employment verification for Jane Doe (E0123)",
      "Registered Nurse",
      "31301",
      "October 7, 2026",
      "To whom it may concern",
      "Sincerely,",
      "People Operations",
      "Waterloo Regional Health Network",
      "Synthetic sample generated by the HR Research Assistant prototype. Not an official WRHN document.",
    ]) {
      expect(text, needle).toContain(needle);
    }
    expect(text).toContain("$52.00 per hour (synthetic sample)");
    expect(text).toContain("37.5 hours per week");
  });
  it("leaves out anything that was not selected", async () => {
    const plain = letterData({
      name: "Sam Roe",
      title: "Personal Support Worker",
      status: "Part-time",
      start: "2021-06-01",
      purpose: "Mortgage",
      include: [],
      addressee: "To whom it may concern",
    });
    const text = pdfText(await readBlob((await letterPdf(plain, "2026-10-07")).blob));
    expect(text).toContain("Re: Employment verification for Sam Roe");
    expect(text).not.toContain("(E");
    expect(text).not.toContain("NOC");
    expect(text).not.toContain("rate of pay");
    expect(text).not.toContain("hours of work");
  });
  it("names the file after the last name and strips odd characters", async () => {
    const r = await letterPdf(
      letterData({
        name: "Ana O'Neil-Smith",
        title: "RN",
        status: "Full-time",
        start: "2020-01-02",
        purpose: "Other",
        purposeOther: "a rental application",
        include: [],
        addressee: "To whom it may concern",
      }),
      "2026-10-07",
    );
    expect(r.filename).toBe("employment-letter-oneil-smith-sample.pdf");
  });
});

describe("form PDFs", () => {
  it("the logo file the PDF and the pages use exists and is a PNG", () => {
    const f = "public/wrhn-logo.png";
    expect(existsSync(f)).toBe(true);
    expect(readFileSync(f).subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  });
  // In Node, jsPDF's save() writes a file into the current directory, so run these in a temp directory.
  const expected = {
    loa: {
      title: "Leave of absence request form",
      fields: [
        "Employee name",
        "Employee ID",
        "Type of leave",
        "Planned first day of leave",
        "Planned return date",
        "Supporting documents attached",
        "Employee signature",
        "Date",
      ],
    },
    benefits: {
      title: "Benefits change form",
      fields: [
        "Employee name",
        "Employee ID",
        "Life event",
        "Date of life event",
        "Dependant name",
        "Relationship",
        "Documents attached",
        "Employee signature",
        "Date",
      ],
    },
    pension: {
      title: "Pension enrolment form",
      fields: [
        "Employee name",
        "Employee ID",
        "Start date",
        "Employment status",
        "Employee signature",
        "Date",
      ],
    },
  } as const;
  it.each(["loa", "benefits", "pension"] as const)(
    "%s form is a one-page US Letter PDF with its title and fields",
    async (id) => {
      const dir = mkdtempSync(join(tmpdir(), "wrhn-form-"));
      const cwd = process.cwd();
      try {
        process.chdir(dir);
        await downloadForm(id);
        const file = join(dir, `${id}-form-sample.pdf`);
        expect(existsSync(file)).toBe(true);
        const text = readFileSync(file).toString("latin1");
        expect(text.startsWith("%PDF-")).toBe(true);
        expect(text).toMatch(/\/MediaBox \[0 0 612\.? 792\.?\]/);
        expect(text.match(/\/Type \/Page\b/g)).toHaveLength(1);
        expect(text).toContain("Synthetic sample form");
        expect(text).toContain(expected[id].title);
        for (const f of expected[id].fields) expect(text, f).toContain(`(${f}) Tj`);
      } finally {
        process.chdir(cwd);
        rmSync(dir, { recursive: true, force: true });
      }
    },
  );
});
