import { clauseById, topics, type Clause, type ClarifyPrompt } from "./hr-research-data";
export type Result={kind:"answered";clause:Clause;context?:Record<string,string>}|{kind:"clarify";prompt:ClarifyPrompt;original:string;context:Record<string,string>}|{kind:"routed";team:string;reason:string;instruction:string}|{kind:"no-clause";reason:string;team:"People Operations supervisor";caution?:string};
export const redact=(value:string)=>{let changed=false; const patterns:[RegExp,string][]=[[/\bE\d{4,6}\b/gi,"[employee ID removed]"],[/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,"[email removed]"],[/(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b/g,"[phone number removed]"]]; let text=value; patterns.forEach(([p,r])=>{if(p.test(text)){changed=true;text=text.replace(p,r)}});return{text,changed}};
const clause=(id:string):Result=>{const found=clauseById(id); if(!found) return {kind:"no-clause",reason:"No approved source covers this question.",team:"People Operations supervisor"}; return {kind:"answered",clause:found}};
const employment=(original:string,accrual=false):ClarifyPrompt=>({id:"employment",question:"Is the employee full-time, part-time or on probation?",field:"Employment type",options:[{label:"Full-time",keywords:["full"],clauseId:accrual?"L21":"L11"},{label:"Part-time",keywords:["part"],clauseId:"L12"},{label:"On probation",keywords:["probation","probationary"],clauseId:"L13"},{label:"Contractor",keywords:["contract"],clauseId:"L14"}]});
const balance:ClarifyPrompt={id:"balance",question:"What do you need to know about the leave balance?",field:"Leave balance topic",options:[{label:"How it accrues",keywords:["accru","earn"],next:employment("",true)},{label:"Carry-over",keywords:["carry"],clauseId:"L31"},{label:"How to check it",keywords:["check","view","find","where"],clauseId:"LFAQ5"}]};
const leaveTopic:ClarifyPrompt={id:"leave-topic",question:"Which leave topic is this about?",field:"Leave topic",options:[{label:"Annual leave entitlement",keywords:["entitle","how many","days"],next:employment("")},{label:"Carry-over",keywords:["carry"],clauseId:"L31"},{label:"Requesting and approval",keywords:["request","approv"],clauseId:"L52"},{label:"Maternity or paternity leave",keywords:["maternity","paternity"],clauseId:"L62"},{label:"Long service",keywords:["long","years"],clauseId:"L64"}]};
const benefits:ClarifyPrompt={id:"benefits",question:"Which benefit is the employee asking about?",field:"Benefit",options:[{label:"Healthcare",keywords:["health"],clauseId:"C_HEALTH"},{label:"Retirement",keywords:["retire","pension"],clauseId:"C_RETIRE"},{label:"Wellbeing",keywords:["well"],clauseId:"C_WELL"},{label:"Insurance",keywords:["insur"],clauseId:"C_INS"},{label:"Allowances",keywords:["allowance","relocat"],clauseId:"C_ALLOW"},{label:"Perks",keywords:["perk","discount"],clauseId:"C_PERKS"}]};
const training:ClarifyPrompt={id:"training-level",question:"What is the employee's role level?",field:"Role level",options:[{label:"Entry-level",keywords:["entry"],clauseId:"T_B_ENTRY"},{label:"Mid-level",keywords:["mid"],clauseId:"T_B_MID"},{label:"Senior-level",keywords:["senior"],clauseId:"T_B_SENIOR"},{label:"Executive-level",keywords:["exec"],clauseId:"T_B_EXEC"}]};
const conduct:ClarifyPrompt={id:"conduct",question:"Which part of the code of conduct is this about?",field:"Code topic",options:[{label:"Gifts",keywords:["gift"],clauseId:"K_GIFT"},{label:"Conflicts of interest",keywords:["conflict"],clauseId:"K_CONFLICT"},{label:"Reporting a concern",keywords:["report","concern"],clauseId:"K_REPORT"},{label:"Company IT and assets",keywords:["it","asset","laptop"],clauseId:"K_IT"},{label:"Confidentiality",keywords:["confiden"],clauseId:"K_CONF"}]};
const retention:ClarifyPrompt={id:"retention",question:"Which records?",field:"Record type",options:[{label:"Employee records",keywords:["employee"],clauseId:"G_RETAIN_EMP"},{label:"Payroll data",keywords:["payroll"],clauseId:"G_RETAIN_PAY"},{label:"Candidate applications",keywords:["candidate","applicant"],clauseId:"G_RETAIN_CAND"},{label:"Performance reviews",keywords:["performance"],clauseId:"G_RETAIN_PERF"}]};
const privacy:ClarifyPrompt={id:"privacy",question:"What does the employee want to do with their personal data?",field:"Data request",options:[{label:"See it",keywords:["see","access","copy","request"],clauseId:"G_ACCESS"},{label:"Correct it",keywords:["correct","wrong","rectif","fix","update"],clauseId:"G_RECT"},{label:"Delete it",keywords:["delete","erase","remove"],clauseId:"G_ERASE"},{label:"Report a breach",keywords:["breach","leak","lost"],clauseId:"G_BREACH"},{label:"Know how long it is kept",keywords:["long","keep","retain"],next:retention}]};
const clarify=(prompt:ClarifyPrompt,original:string):Result=>({kind:"clarify",prompt,original,context:{}});
export function matchQuestion(input:string):Result{const t=input.toLowerCase();
 const sensitive:[string[],string,string][]=[[["grievance","disciplin","terminat","dismiss","investigation","whistle"],"Labour Relations","This needs a person's judgment and confidentiality."],[["harass"],"Labour and Employee Relations","This needs a person's judgment and confidentiality."],[["accommodat","medical","disabilit"],"Health and Wellness","This needs a person's judgment and confidentiality."],[["union","collective agreement","bargaining"],"Labour Relations","Collective agreements are not loaded in this prototype's dataset yet."]];
 for(const [keys,team,reason] of sensitive) if(keys.some(k=>t.includes(k))) return{kind:"routed",team,reason,instruction:`This needs a person's judgment and confidentiality. Pass the question to ${team} and do not reply with policy wording.`};
 if(["payslip","pay stub","tax form","direct deposit","payroll"].some(k=>t.includes(k)))return{kind:"routed",team:"Payroll",reason:"None of the loaded policies has a clause about this.",instruction:"Payroll updates are not an HR task. Send the employee to Payroll with the steps for changing their details."};
 if(["10 years","ten years","long service","years of service"].some(k=>t.includes(k)))return clause("L64");
 if(["carry over","carry-over","carryover","forfeit","unused leave"].some(k=>t.includes(k)))return clause(t.includes("exceed")?"L33":"L31");
 if(t.includes("leave")&&["approve","approval","how long does leave","escalat","denied","appeal"].some(k=>t.includes(k)))return clause(t.includes("denied")||t.includes("appeal")?"L53":"L52");
 if(t.includes("maternity")||t.includes("paternity"))return clause("L62"); if(t.includes("public holiday"))return clause("L61"); if(t.includes("unpaid leave"))return clause("L63");
 if(t.includes("leave/balance")||t.includes("leave balance"))return clarify(balance,input);
 const leaveMatch=["annual leave","vacation","days of leave","leave entitlement","leave days","accrue","accrual","leave/policy"].some(k=>t.includes(k));
 if(leaveMatch){if(t.includes("part-time"))return clause("L12"); if(t.includes("probation"))return clause("L13"); if(t.includes("contractor"))return clause("L14"); if(t.includes("full-time"))return clause(t.includes("accru")||t.includes("accrual")?"L21":"L11"); if(t.includes("leave/policy")||(!/[?]|how many|entitle|accru|days/.test(t)))return clarify(leaveTopic,input); return clarify(employment(input,t.includes("accru")||t.includes("accrual")),input)}
 const pairs:[string[],string][]=[[["health","dental","vision","benefits/health"],"C_HEALTH"],[["wellbeing","wellness","gym","benefits/wellbeing"],"C_WELL"],[["retirement","pension","401"],"C_RETIRE"],[["insurance","disability"],"C_INS"],[["relocation","allowance"],"C_ALLOW"],[["perk","discount"],"C_PERKS"],[["mid-year"],"C_MID"],[["probation raise","raise after probation"],"C_PROB"],[["bonus"],"C_BONUS"],[["parental"],"C_PARENT"],[["sick pay","sick leave"],"C_SICK"],[["salary review","pay review","how often are salary"],"C_REVIEW"]]; for(const [keys,id] of pairs)if(keys.some(k=>t.includes(k)))return clause(id); if(t.includes("remote")&&["pay","salary","compensation"].some(k=>t.includes(k)))return clause("C_REMOTE"); if(t.includes("benefit"))return clarify(benefits,input);
 if((t.includes("training")||t.includes("learning"))&&t.includes("budget")){if(t.includes("carry"))return clause("T_CARRY");for(const [k,id] of [["entry","T_B_ENTRY"],["mid","T_B_MID"],["senior","T_B_SENIOR"],["exec","T_B_EXEC"]])if(t.includes(k))return clause(id);return clarify(training,input)}
 if(t.includes("reimburse"))return clause("T_REIMB"); if(t.includes("request training")||t.includes("request a course"))return clause("T_REQ"); if(t.includes("denied")&&t.includes("training"))return clause("T_DENIED"); if(t.includes("mandatory")||t.includes("training/mandatory"))return clause("T_MAND");
 const conductPairs:[string[],string][]=[[["gift"],"K_GIFT"],[["conflict"],"K_CONFLICT"],[["protected","retaliat"],"K_PROTECT"],[["report","unethical"],"K_REPORT"],[["it resources","company assets","laptop","software"],"K_IT"],[["confidential"],"K_CONF"]];for(const [keys,id]of conductPairs)if(keys.some(k=>t.includes(k)))return clause(id);if(["code of conduct","policy/code of conduct","conduct"].some(k=>t.includes(k)))return clarify(conduct,input);
 if(t.includes("breach"))return clause("G_BREACH");if(t.includes("how long")&&["keep","retain","retention"].some(k=>t.includes(k)))return clarify(retention,input);if(["how quickly","timeline","respond to a data request"].some(k=>t.includes(k)))return clause("G_TIME");if(["gdpr","policy/gdpr","personal data","data privacy","dsar","data request"].some(k=>t.includes(k)))return clarify(privacy,input);
 if(["travel","expense","remote work","flexible work","performance review","security","acceptable use","diversity","equal opportunity","health and safety","onboarding","exit"].some(k=>t.includes(k)))return{kind:"no-clause",reason:"This policy is in the dataset, but its clause text is not loaded into this prototype yet.",team:"People Operations supervisor"};
 const caution=["referral","recruitment","other/question"].some(k=>t.includes(k))?"This inquiry has no related policy in the dataset. Unmapped tickets are not verified no-answer cases, so a person should review it.":undefined;return{kind:"no-clause",reason:"No approved source covers this question.",team:"People Operations supervisor",caution};}
export function answerFollowUp(result:Extract<Result,{kind:"clarify"}>,answer:string):Result{const t=answer.toLowerCase();const option=result.prompt.options.find(o=>o.label.toLowerCase()===t||o.keywords.some(k=>t.includes(k)));if(option){const context={...result.context,[result.prompt.field]:option.label};if(option.next)return{kind:"clarify",prompt:option.next,original:result.original,context};const found=option.clauseId&&clauseById(option.clauseId);return found?{kind:"answered",clause:found,context}:{kind:"no-clause",reason:"No approved source covers this question.",team:"People Operations supervisor"}}const fresh=matchQuestion(answer);if(fresh.kind!=="no-clause"||answer.includes("?"))return fresh;return{...result,prompt:{...result.prompt,question:"I did not catch that. Choose one of these:"}}}
export const hasDifferentTopic=(text:string)=>topics.some(topic=>topic.keywords.some(k=>text.toLowerCase().includes(k)));
