import { syntheticClauses, syntheticPolicies } from "./hr-flow-data";
export type Policy = { file: string; title: string; version: string; effectiveDate: string; effectiveNote: string; linkedTickets: number; loaded: boolean; handling: string; synthetic?: boolean | undefined };
export type Clause = { id: string; policyFile: string; ref: string; text: string; note?: string | undefined; related?: string[] | undefined; tableRow?: boolean | undefined };
export type ClarifyOption = { label: string; keywords: string[]; clauseId?: string; next?: ClarifyPrompt };
export type ClarifyPrompt = { id: string; question: string; field: string; options: ClarifyOption[] };
export type Topic = { id: string; keywords: string[] };
export type Ticket = { id: string; subject: string; department: string; status: string; category: string; candidateLabel?: string; description: string };
export type ReviewItem = { id: string; question: string; verdict: string; clause: string; date: string; status: "Open" | "Reviewed" };
export type DatasetCheck = { id: string; ticketId: string; ticketLabel: string; retrievedPolicy: string; result: "Match" | "Different" };

const loaded = (file:string,title:string,linkedTickets:number):Policy => ({file,title,version:"2025-01",effectiveDate:"Not stated in the document",effectiveNote:file.includes("leave")||file.includes("compensation")||file.includes("privacy")?"Placeholder in the document":"No effective date in the document",linkedTickets,loaded:true,handling:"Answered with a quote"});
const unloaded = (file:string,title:string,handling="Not loaded in prototype"):Policy => ({file,title,version:"Not read in prototype",effectiveDate:"Not read in prototype",effectiveNote:"Not read in prototype",linkedTickets:0,loaded:false,handling});
export const policies: Policy[] = [
 loaded("leave_policy_en.docx","Annual Leave Policy",22), loaded("compensation_benefits_policy_en.docx","Compensation & Benefits Policy",84), loaded("code_of_conduct_en.docx","Code of Conduct & Ethics Policy",29), loaded("training_development_policy_en.docx","Training & Development Policy",20), loaded("data_privacy_gdpr_policy_en.docx","Data Privacy & GDPR Policy",0),
 unloaded("dei_policy_en.docx","DEI policy"), unloaded("anti_harassment_policy_en.docx","Anti-harassment policy","Routed to a person"), unloaded("travel_expense_policy_en.docx","Travel and expense policy"), unloaded("whistleblowing_policy_en.docx","Whistleblowing policy","Routed to a person"), unloaded("remote_work_policy_en.docx","Remote work policy"), unloaded("it_security_acceptable_use_en.docx","IT security and acceptable use policy"), unloaded("performance_review_policy_en.docx","Performance review policy"), unloaded("flexible_work_policy_en.docx","Flexible work policy"), unloaded("termination_exit_policy_en.docx","Termination and exit policy","Routed to a person"), unloaded("equal_opportunity_policy_en.docx","Equal opportunity policy"), unloaded("recruitment_onboarding_policy_en.docx","Recruitment and onboarding policy"), unloaded("grievance_disciplinary_policy_en.docx","Grievance and disciplinary policy","Routed to a person"), unloaded("health_safety_policy_en.docx","Health and safety policy"),
 ...syntheticPolicies
];
const benefitNote='Benefits may vary by location and role. Source: Extended FAQ, question 4: "Benefits may vary by location and role, but core offerings are consistent across the organization." Confirm the employee\'s role before replying.';
const c=(id:string,policyFile:string,ref:string,text:string,note?:string,related?:string[],tableRow=false):Clause=>({id,policyFile,ref,text,note,related,tableRow});
export const clauses: Clause[] = [
 c("L11","leave_policy_en.docx","1.1 Full-Time Employees","Full-time employees are entitled to an annual leave of 26 days per year. This leave is accrued monthly, starting from the first day of employment.",undefined,["What happens at 10 years of service for annual leave?","How does annual leave carry over?"]),
 c("L12","leave_policy_en.docx","1.2 Part-Time Employees","Part-time employees will accrue annual leave on a pro-rata basis, calculated according to their contracted hours. For example, if a part-time employee works 20 hours a week, they will receive 13 days of annual leave per year.",undefined,["What happens at 10 years of service for annual leave?","How does annual leave carry over?"]),
 c("L13","leave_policy_en.docx","1.3 Probationary Employees","Employees on probation are entitled to annual leave, which will be accrued at a rate of 1.5 days per month during the probation period. Upon successful completion of probation, the employee will transition to the full entitlement."),
 c("L14","leave_policy_en.docx","1.4 Contractors","Contractors are not eligible for annual leave benefits. However, they may negotiate time off within their contract terms."),
 c("L21","leave_policy_en.docx","2.1 Standard Accrual","Full-Time Employees: 2.17 days per month (26 days annually)"),
 c("L31","leave_policy_en.docx","3.1 Carry-Over Rules","Employees may carry over a maximum of 10 unused annual leave days into the next calendar year. Any unused days beyond this limit will be forfeited unless otherwise agreed upon by management.",undefined,["What happens if the employee exceeds the carry-over limit?"]),
 c("L33","leave_policy_en.docx","3.3 Exceeding Maximums","If an employee exceeds the carry-over limit, they will receive a notification from HR. The employee must use the excess days within the next six months or risk forfeiture."),
 c("L52","leave_policy_en.docx","5.2 Timeframe","Requests should be approved or denied within 5 business days. If a supervisor does not respond within this timeframe, the request will be automatically escalated to the next level of management.",undefined,["What if a leave request is denied?"]),
 c("L53","leave_policy_en.docx","5.3 Escalation Process","If a request is denied, the employee can appeal to HR within 3 business days of the denial. HR will review the appeal and provide a final decision within 5 business days."),
 c("L61","leave_policy_en.docx","6.1 Public Holidays","If a public holiday falls within an employee's scheduled leave, that day will not be deducted from their annual leave balance."),
 c("L62","leave_policy_en.docx","6.2 Maternity/Paternity Leave","Employees on maternity or paternity leave will not accrue annual leave during their leave period. However, upon return, they will receive a one-time credit of 5 additional days."),
 c("L63","leave_policy_en.docx","6.3 Unpaid Leave","Employees on unpaid leave will not accrue annual leave during the unpaid period."),
 c("L64","leave_policy_en.docx","6.4 Long Service Awards","Employees who have completed 10 years of service will receive an additional 5 days of annual leave as a long service award.",undefined,["How does annual leave carry over?","How many days of annual leave does a full-time employee get?"]),
 c("LFAQ5","leave_policy_en.docx","Appendix, FAQ A5","You can check your leave balance in the HRIS or contact HR for assistance."),
 c("C_HEALTH","compensation_benefits_policy_en.docx","Benefits > Healthcare","Comprehensive healthcare plans, including medical, dental, and vision coverage.",benefitNote,["How does remote work affect pay?","How often are salary reviews held?"]),
 c("C_RETIRE","compensation_benefits_policy_en.docx","Benefits > Retirement","Retirement savings plans with company matching contributions.",benefitNote), c("C_WELL","compensation_benefits_policy_en.docx","Benefits > Wellbeing","Programs promoting physical and mental health, including gym memberships and wellness workshops.",benefitNote), c("C_INS","compensation_benefits_policy_en.docx","Benefits > Insurance","Life and disability insurance coverage for all employees."), c("C_ALLOW","compensation_benefits_policy_en.docx","Benefits > Allowances","Travel and relocation allowances for employees required to move for work.",benefitNote), c("C_PERKS","compensation_benefits_policy_en.docx","Benefits > Perks","Employee discounts, flexible work arrangements, and professional development opportunities.",benefitNote),
 c("C_REVIEW","compensation_benefits_policy_en.docx","Pay Review Process > Annual Cycle","Conduct annual salary reviews in Q4, with adjustments effective from January 1."), c("C_MID","compensation_benefits_policy_en.docx","Pay Review Process > Mid-Year Adjustments","Allow for mid-year salary adjustments in cases of significant changes in job responsibilities or market conditions."), c("C_PROB","compensation_benefits_policy_en.docx","Pay Review Process > Probation Raises","Employees completing their probation period will be reviewed for potential salary increases based on performance and role alignment."), c("C_BONUS","compensation_benefits_policy_en.docx","Bonus & Incentive Programs > Performance-Based Bonuses","Annual bonuses based on individual and company performance metrics."), c("C_PARENT","compensation_benefits_policy_en.docx","Leave Entitlements Connected to Compensation > Parental Leave","Paid parental leave for both primary and secondary caregivers, exceeding legal minimums."), c("C_SICK","compensation_benefits_policy_en.docx","Leave Entitlements Connected to Compensation > Sick Pay","Paid sick leave policy ensuring employees can take necessary time off without financial penalty."), c("C_REMOTE","compensation_benefits_policy_en.docx","Geographic/Remote Work Adjustments","Compensation for remote employees will be adjusted based on the cost of living in their location."),
 c("K_GIFT","code_of_conduct_en.docx","Conflicts of Interest > Prohibited Activities","Accepting gifts from clients or suppliers that exceed a nominal value.",'Appendix FAQ 2 adds: "Only nominal gifts are acceptable; anything beyond that must be reported."',["What must an employee disclose about conflicts of interest?"]), c("K_CONFLICT","code_of_conduct_en.docx","Conflicts of Interest > Disclosure Process","Employees must disclose any potential conflicts to their manager or HR."), c("K_REPORT","code_of_conduct_en.docx","Reporting Concerns and Whistleblower Protections","Employees are encouraged to report any unethical behavior or violations of this policy.",undefined,["Is the employee protected if they report a concern?"]), c("K_PROTECT","code_of_conduct_en.docx","Reporting Concerns and Whistleblower Protections > Protections","Employees who report concerns in good faith will not face retaliation."), c("K_IT","code_of_conduct_en.docx","Use of Company Assets and IT Resources","Company assets, including IT resources, should be used responsibly and primarily for business purposes."), c("K_CONF","code_of_conduct_en.docx","Confidentiality and Data Protection Obligations","Employees must protect sensitive information related to the company, clients, and colleagues."),
 c("T_MAND","training_development_policy_en.docx","Appendix, FAQ question 1","Compliance, security, onboarding, and health & safety training are mandatory for all employees.",undefined,["How does the employee request optional training?"]), c("T_REQ","training_development_policy_en.docx","Appendix, FAQ question 2","Complete a training request form and submit it to your manager for approval."), c("T_B_ENTRY","training_development_policy_en.docx","Learning Budget Management > budget table (Role Level, Annual Training Budget Limit)","Entry-Level | $1,000",undefined,undefined,true), c("T_B_MID","training_development_policy_en.docx","Learning Budget Management > budget table (Role Level, Annual Training Budget Limit)","Mid-Level | $1,500",undefined,undefined,true), c("T_B_SENIOR","training_development_policy_en.docx","Learning Budget Management > budget table (Role Level, Annual Training Budget Limit)","Senior-Level | $2,500",undefined,undefined,true), c("T_B_EXEC","training_development_policy_en.docx","Learning Budget Management > budget table (Role Level, Annual Training Budget Limit)","Executive-Level | $5,000",undefined,undefined,true), c("T_CARRY","training_development_policy_en.docx","Learning Budget Management > Carryover Rules","Unused training budgets may be carried over to the next fiscal year, subject to managerial approval."), c("T_REIMB","training_development_policy_en.docx","Reimbursement Process for External Training","Submit receipts to HR for reimbursement within 30 days of completion."), c("T_DENIED","training_development_policy_en.docx","Appendix, FAQ question 6","You may discuss the reasons with your manager and explore alternative training options."),
 c("G_ACCESS","data_privacy_gdpr_policy_en.docx","Data Subject Rights","Right of Access: The right to request access to personal data.",undefined,["How quickly must a data request be answered?"]), c("G_RECT","data_privacy_gdpr_policy_en.docx","Data Subject Rights","Right to Rectification: The right to request correction of inaccurate personal data.",undefined,["How quickly must a data request be answered?"]), c("G_ERASE","data_privacy_gdpr_policy_en.docx","Data Subject Rights","Right to Erasure: The right to request deletion of personal data.",undefined,["How quickly must a data request be answered?"]), c("G_TIME","data_privacy_gdpr_policy_en.docx","Data Subject Rights > Handling Timelines","Requests will be acknowledged within 5 business days. Responses will be provided within 30 days, extendable to 60 days for complex requests."), c("G_BREACH","data_privacy_gdpr_policy_en.docx","Incident & Breach Notification","Notification: Notify the relevant authorities within 72 hours and affected individuals as required."), c("G_RETAIN_EMP","data_privacy_gdpr_policy_en.docx","Retention & Deletion > Retention Schedule","Employee Records | 7 years post-employment",undefined,undefined,true), c("G_RETAIN_PAY","data_privacy_gdpr_policy_en.docx","Retention & Deletion > Retention Schedule","Payroll Data | 7 years",undefined,undefined,true), c("G_RETAIN_CAND","data_privacy_gdpr_policy_en.docx","Retention & Deletion > Retention Schedule","Candidate Applications | 1 year",undefined,undefined,true), c("G_RETAIN_PERF","data_privacy_gdpr_policy_en.docx","Retention & Deletion > Retention Schedule","Performance Reviews | 3 years",undefined,undefined,true)
 ,...syntheticClauses
];
export const clauseById=(id:string)=>clauses.find(x=>x.id===id);
export const policyByFile=(file:string)=>policies.find(x=>x.file===file);
export const tickets:Ticket[]=[
 {id:"HR-202501-0006",subject:"Leave – Balance assistance",department:"Marketing",status:"Waiting for Employee",category:"Leave/Balance",candidateLabel:"leave_policy_en.docx",description:"User E0064 requests help regarding Leave/Balance."}, {id:"HR-202501-0009",subject:"Leave – Policy assistance",department:"Operations",status:"Resolved",category:"Leave/Policy",candidateLabel:"leave_policy_en.docx",description:"User E0046 requests help regarding Leave/Policy."}, {id:"HR-202501-0007",subject:"Benefits – Health assistance",department:"Sales",status:"Open",category:"Benefits/Health",candidateLabel:"compensation_benefits_policy_en.docx",description:"User E0115 requests help regarding Benefits/Health."}, {id:"HR-202501-0003",subject:"Benefits – Wellbeing assistance",department:"IT",status:"Resolved",category:"Benefits/Wellbeing",candidateLabel:"compensation_benefits_policy_en.docx",description:"User E0062 requests help regarding Benefits/Wellbeing."}, {id:"HR-202501-0001",subject:"Payroll – Payslip assistance",department:"IT",status:"Closed",category:"Payroll/Payslip",candidateLabel:"compensation_benefits_policy_en.docx",description:"User E0040 requests help regarding Payroll/Payslip."}, {id:"HR-202501-0027",subject:"Training – Mandatory assistance",department:"Finance",status:"Resolved",category:"Training/Mandatory",candidateLabel:"training_development_policy_en.docx",description:"User E0006 requests help regarding Training/Mandatory."}, {id:"HR-202501-0002",subject:"Policy – GDPR assistance",department:"Finance",status:"In Progress",category:"Policy/GDPR",candidateLabel:"code_of_conduct_en.docx",description:"User E0061 requests help regarding Policy/GDPR."}, {id:"HR-202501-0011",subject:"Policy – Code of Conduct assistance",department:"Sales",status:"In Progress",category:"Policy/Code of Conduct",candidateLabel:"code_of_conduct_en.docx",description:"User E0019 requests help regarding Policy/Code of Conduct."}, {id:"HR-202501-0005",subject:"Recruitment – Referral assistance",department:"Operations",status:"Open",category:"Recruitment/Referral",description:"User E0098 requests help regarding Recruitment/Referral."}, {id:"HR-202501-0010",subject:"Other – Question assistance",department:"Finance",status:"Open",category:"Other/Question",description:"User E0101 requests help regarding Other/Question."}
];
export const seedReviews:ReviewItem[]=[{id:"r1",question:"Leave – Balance assistance (HR-202501-0006)",verdict:"Missing something",clause:"Appendix, FAQ A5",date:"2026-10-05",status:"Open"},{id:"r2",question:"Leave – Balance assistance (HR-202501-0006)",verdict:"Missing something",clause:"Appendix, FAQ A5",date:"2026-10-04",status:"Open"},{id:"r3",question:"Payroll – Payslip assistance (HR-202501-0001)",verdict:"Wrong clause",clause:"No clause",date:"2026-10-03",status:"Reviewed"}];
export const seedChecks:DatasetCheck[]=[{id:"d1",ticketId:"HR-202501-0002",ticketLabel:"code_of_conduct_en.docx",retrievedPolicy:"data_privacy_gdpr_policy_en.docx",result:"Different"},{id:"d2",ticketId:"HR-202501-0001",ticketLabel:"compensation_benefits_policy_en.docx",retrievedPolicy:"none (no clause)",result:"Different"},{id:"d3",ticketId:"HR-202501-0007",ticketLabel:"compensation_benefits_policy_en.docx",retrievedPolicy:"compensation_benefits_policy_en.docx",result:"Match"}];
export const tryQuestions=["How many days of annual leave does a part-time employee get?","What happens at 10 years of service for annual leave?","How much is the training budget?","An employee is asking about their active grievance. What should I tell them?"];
export const topics:Topic[]=[{id:"long-service",keywords:["10 years","ten years","long service","years of service"]},{id:"carry-over",keywords:["carry over","carry-over","carryover","forfeit","unused leave"]},{id:"leave-balance",keywords:["leave/balance","leave balance"]},{id:"leave-entitlement",keywords:["annual leave","vacation","days of leave","leave entitlement","leave days","accrue","accrual","leave/policy"]},{id:"benefits",keywords:["benefit"]},{id:"privacy",keywords:["gdpr","personal data","data privacy","dsar","data request"]}];
