/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantReviewRouteImport } from './routes/assistant.review'
import { Route as AssistantSourcesRouteImport } from './routes/assistant.sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantReviewRoute = AssistantReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantSourcesRoute = AssistantSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AssistantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/assistant/review': typeof AssistantReviewRoute
  '/assistant/sources': typeof AssistantSourcesRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant/review': typeof AssistantReviewRoute
  '/assistant/sources': typeof AssistantSourcesRoute
  '/assistant': typeof AssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/assistant/review': typeof AssistantReviewRoute
  '/assistant/sources': typeof AssistantSourcesRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/assistant/review'
    | '/assistant/sources'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistant/review' | '/assistant/sources' | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/assistant/review'
    | '/assistant/sources'
    | '/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/review': {
      id: '/assistant/review'
      path: '/review'
      fullPath: '/assistant/review'
      preLoaderRoute: typeof AssistantReviewRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/sources': {
      id: '/assistant/sources'
      path: '/sources'
      fullPath: '/assistant/sources'
      preLoaderRoute: typeof AssistantSourcesRouteImport
      parentRoute: typeof AssistantRoute
    }
  }
}

interface AssistantRouteChildren {
  AssistantReviewRoute: typeof AssistantReviewRoute
  AssistantSourcesRoute: typeof AssistantSourcesRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantReviewRoute: AssistantReviewRoute,
  AssistantSourcesRoute: AssistantSourcesRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
